//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalStreetDataCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalStreetDataCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GeographicStreetAxis" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}GeographicStreetAxisCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalStreetDataCType", propOrder = {
    "geographicStreetAxis"
})
public class AdditionalStreetDataCType {

    @XmlElement(name = "GeographicStreetAxis")
    protected GeographicStreetAxisCType geographicStreetAxis;

    /**
     * Gets the value of the geographicStreetAxis property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicStreetAxisCType }
     *     
     */
    public GeographicStreetAxisCType getGeographicStreetAxis() {
        return geographicStreetAxis;
    }

    /**
     * Sets the value of the geographicStreetAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicStreetAxisCType }
     *     
     */
    public void setGeographicStreetAxis(GeographicStreetAxisCType value) {
        this.geographicStreetAxis = value;
    }

}
