//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AddressTypeCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressTypeCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AddressClass" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType" minOccurs="0"/&gt;
 *         &lt;element name="AddressRecordDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="AddressRecordDateTermination" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressTypeCType", propOrder = {
    "addressClass",
    "addressRecordDate",
    "addressRecordDateTermination"
})
public class AddressTypeCType {

    @XmlElement(name = "AddressClass")
    protected CodelistDataElementCType addressClass;
    @XmlElement(name = "AddressRecordDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar addressRecordDate;
    @XmlElement(name = "AddressRecordDateTermination")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar addressRecordDateTermination;

    /**
     * Gets the value of the addressClass property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public CodelistDataElementCType getAddressClass() {
        return addressClass;
    }

    /**
     * Sets the value of the addressClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public void setAddressClass(CodelistDataElementCType value) {
        this.addressClass = value;
    }

    /**
     * Gets the value of the addressRecordDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAddressRecordDate() {
        return addressRecordDate;
    }

    /**
     * Sets the value of the addressRecordDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAddressRecordDate(XMLGregorianCalendar value) {
        this.addressRecordDate = value;
    }

    /**
     * Gets the value of the addressRecordDateTermination property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAddressRecordDateTermination() {
        return addressRecordDateTermination;
    }

    /**
     * Sets the value of the addressRecordDateTermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAddressRecordDateTermination(XMLGregorianCalendar value) {
        this.addressRecordDateTermination = value;
    }

}
