//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodelistCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodelistCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CodelistCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CodelistItem" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistItemCType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodelistCType", propOrder = {
    "codelistCode",
    "codelistItem"
})
public class CodelistCType {

    @XmlElement(name = "CodelistCode", required = true)
    protected String codelistCode;
    @XmlElement(name = "CodelistItem", required = true)
    protected CodelistItemCType codelistItem;

    /**
     * Gets the value of the codelistCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodelistCode() {
        return codelistCode;
    }

    /**
     * Sets the value of the codelistCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodCiselnika(String value) {
        this.codelistCode = value;
    }

    /**
     * Gets the value of the codelistItem property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistItemCType }
     *     
     */
    public CodelistItemCType getCodelistItem() {
        return codelistItem;
    }

    /**
     * Sets the value of the codelistItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistItemCType }
     *     
     */
    public void setCodelistItem(CodelistItemCType value) {
        this.codelistItem = value;
    }

}
