//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodelistDataElementCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodelistDataElementCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NonCodelistData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Codelist" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodelistDataElementCType", propOrder = {
    "nonCodelistData",
    "codelist"
})
@XmlSeeAlso({
    DistrictCType.class,
    AffixCType.class
})
public class CodelistDataElementCType {

    @XmlElement(name = "NonCodelistData")
    protected String nonCodelistData;
    @XmlElement(name = "Codelist")
    protected CodelistCType codelist;

    /**
     * Gets the value of the nonCodelistData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonCodelistData() {
        return nonCodelistData;
    }

    /**
     * Sets the value of the nonCodelistData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonCodelistData(String value) {
        this.nonCodelistData = value;
    }

    /**
     * Gets the value of the codelist property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistCType }
     *     
     */
    public CodelistCType getCodelist() {
        return codelist;
    }

    /**
     * Sets the value of the codelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistCType }
     *     
     */
    public void setCodelist(CodelistCType value) {
        this.codelist = value;
    }

}
