//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistrictCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DistrictCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="UniqueNumbering" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistrictCType")
public class DistrictCType
    extends CodelistDataElementCType
{

    @XmlAttribute(name = "UniqueNumbering", required = true)
    protected boolean uniqueNumbering;

    /**
     * Gets the value of the uniqueNumbering property.
     * 
     */
    public boolean isUniqueNumbering() {
        return uniqueNumbering;
    }

    /**
     * Sets the value of the uniqueNumbering property.
     * 
     */
    public void setUniqueNumbering(boolean value) {
        this.uniqueNumbering = value;
    }

}
