//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for GeographicStreetAxisCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeographicStreetAxisCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StreetAxisID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StreetAxisStart" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}StreetAxisStartCType" minOccurs="0"/&gt;
 *         &lt;element name="StreetAxisEnd" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}StreetAxisEndCType" minOccurs="0"/&gt;
 *         &lt;element name="StreetAxisNode" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}StreetAxisNodeCType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicStreetAxisCType", propOrder = {
    "streetAxisID",
    "streetAxisStart",
    "streetAxisEnd",
    "streetAxisNode"
})
public class GeographicStreetAxisCType {

    @XmlElement(name = "StreetAxisID")
    protected String streetAxisID;
    @XmlElement(name = "StreetAxisStart")
    protected StreetAxisStartCType streetAxisStart;
    @XmlElement(name = "StreetAxisEnd")
    protected StreetAxisEndCType streetAxisEnd;
    @XmlElement(name = "StreetAxisNode")
    protected List<StreetAxisNodeCType> streetAxisNode;

    /**
     * Gets the value of the streetAxisID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAxisID() {
        return streetAxisID;
    }

    /**
     * Sets the value of the streetAxisID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAxisID(String value) {
        this.streetAxisID = value;
    }

    /**
     * Gets the value of the streetAxisStart property.
     * 
     * @return
     *     possible object is
     *     {@link StreetAxisStartCType }
     *     
     */
    public StreetAxisStartCType getStreetAxisStart() {
        return streetAxisStart;
    }

    /**
     * Sets the value of the streetAxisStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetAxisStartCType }
     *     
     */
    public void setStreetAxisStart(StreetAxisStartCType value) {
        this.streetAxisStart = value;
    }

    /**
     * Gets the value of the streetAxisEnd property.
     * 
     * @return
     *     possible object is
     *     {@link StreetAxisEndCType }
     *     
     */
    public StreetAxisEndCType getStreetAxisEnd() {
        return streetAxisEnd;
    }

    /**
     * Sets the value of the streetAxisEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetAxisEndCType }
     *     
     */
    public void setStreetAxisEnd(StreetAxisEndCType value) {
        this.streetAxisEnd = value;
    }

    /**
     * Gets the value of the streetAxisNode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the streetAxisNode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStreetAxisNode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreetAxisNodeCType }
     * 
     * 
     */
    public List<StreetAxisNodeCType> getStreetAxisNode() {
        if (streetAxisNode == null) {
            streetAxisNode = new ArrayList<StreetAxisNodeCType>();
        }
        return this.streetAxisNode;
    }

}
