//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.uvzsr.is.reg.model.ra package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.uvzsr.is.reg.model.ra
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DistrictCType }
     * 
     */
    public DistrictCType createDistrictCType() {
        return new DistrictCType();
    }

    /**
     * Create an instance of {@link BuildingUnitSCType }
     * 
     */
    public BuildingUnitSCType createBuildingUnitSCType() {
        return new BuildingUnitSCType();
    }

    /**
     * Create an instance of {@link CorporateBodyFullNameSCType }
     * 
     */
    public CorporateBodyFullNameSCType createCorporateBodyFullNameSCType() {
        return new CorporateBodyFullNameSCType();
    }

    /**
     * Create an instance of {@link CodelistItemCType }
     * 
     */
    public CodelistItemCType createCodelistItemCType() {
        return new CodelistItemCType();
    }

    /**
     * Create an instance of {@link RecipientCType }
     * 
     */
    public RecipientCType createRecipientCType() {
        return new RecipientCType();
    }

    /**
     * Create an instance of {@link AffixCType }
     * 
     */
    public AffixCType createAffixCType() {
        return new AffixCType();
    }

    /**
     * Create an instance of {@link GivenFamilyNameSCType }
     * 
     */
    public GivenFamilyNameSCType createGivenFamilyNameSCType() {
        return new GivenFamilyNameSCType();
    }

    /**
     * Create an instance of {@link AddressPointCType }
     * 
     */
    public AddressPointCType createAddressPointCType() {
        return new AddressPointCType();
    }

    /**
     * Create an instance of {@link AddressTypeCType }
     * 
     */
    public AddressTypeCType createAddressTypeCType() {
        return new AddressTypeCType();
    }

    /**
     * Create an instance of {@link FamilyNameSCType }
     * 
     */
    public FamilyNameSCType createFamilyNameSCType() {
        return new FamilyNameSCType();
    }

    /**
     * Create an instance of {@link DeliveryAddressCType }
     * 
     */
    public DeliveryAddressCType createDeliveryAddressCType() {
        return new DeliveryAddressCType();
    }

    /**
     * Create an instance of {@link CodelistDataElementCType }
     * 
     */
    public CodelistDataElementCType createCodelistDataElementCType() {
        return new CodelistDataElementCType();
    }

    /**
     * Create an instance of {@link GeographicStreetAxisCType }
     * 
     */
    public GeographicStreetAxisCType createGeographicStreetAxisCType() {
        return new GeographicStreetAxisCType();
    }

    /**
     * Create an instance of {@link StreetAxisNodeCType }
     * 
     */
    public StreetAxisNodeCType createStreetAxisNodeCType() {
        return new StreetAxisNodeCType();
    }

    /**
     * Create an instance of {@link StreetAxisEndCType }
     * 
     */
    public StreetAxisEndCType createStreetAxisEndCType() {
        return new StreetAxisEndCType();
    }

    /**
     * Create an instance of {@link PhysicalAddressCType }
     * 
     */
    public PhysicalAddressCType createPhysicalAddressCType() {
        return new PhysicalAddressCType();
    }

    /**
     * Create an instance of {@link CodelistCType }
     * 
     */
    public CodelistCType createCodelistCType() {
        return new CodelistCType();
    }

    /**
     * Create an instance of {@link AdditionalStreetDataCType }
     * 
     */
    public AdditionalStreetDataCType createAdditionalStreetDataCType() {
        return new AdditionalStreetDataCType();
    }

    /**
     * Create an instance of {@link OrganizationUnitNameSCType }
     * 
     */
    public OrganizationUnitNameSCType createOrganizationUnitNameSCType() {
        return new OrganizationUnitNameSCType();
    }

    /**
     * Create an instance of {@link StreetAxisStartCType }
     * 
     */
    public StreetAxisStartCType createStreetAxisStartCType() {
        return new StreetAxisStartCType();
    }

    /**
     * Create an instance of {@link XYHCType }
     * 
     */
    public XYHCType createXYHCType() {
        return new XYHCType();
    }

    /**
     * Create an instance of {@link BLHCType }
     * 
     */
    public BLHCType createBLHCType() {
        return new BLHCType();
    }

    /**
     * Create an instance of {@link BuildingCType }
     * 
     */
    public BuildingCType createBuildingCType() {
        return new BuildingCType();
    }

    /**
     * Create an instance of {@link PersonNameCType }
     * 
     */
    public PersonNameCType createPersonNameCType() {
        return new PersonNameCType();
    }

}
