//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for PhysicalAddressCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalAddressCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FamilyName" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}FamilyNameSCType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Country" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType" minOccurs="0"/&gt;
 *         &lt;element name="Region" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType" minOccurs="0"/&gt;
 *         &lt;element name="County" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType" minOccurs="0"/&gt;
 *         &lt;element name="Municipality" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CodelistDataElementCType" minOccurs="0"/&gt;
 *         &lt;element name="District" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}DistrictCType" minOccurs="0"/&gt;
 *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalStreetData" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}AdditionalStreetDataCType" minOccurs="0"/&gt;
 *         &lt;element name="BuildingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PropertyRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="AddressPoint" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}AddressPointCType" minOccurs="0"/&gt;
 *         &lt;element name="BuildingIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryAddress" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}DeliveryAddressCType" minOccurs="0"/&gt;
 *         &lt;element name="Building" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}BuildingCType" minOccurs="0"/&gt;
 *         &lt;element name="AddressType" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}AddressTypeCType" minOccurs="0"/&gt;
 *         &lt;element name="BuildingUnit" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}BuildingUnitSCType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalAddressCType", propOrder = {
    "familyName",
    "addressLine",
    "country",
    "region",
    "county",
    "municipality",
    "district",
    "streetName",
    "additionalStreetData",
    "buildingNumber",
    "propertyRegistrationNumber",
    "addressPoint",
    "buildingIndex",
    "deliveryAddress",
    "building",
    "addressType",
    "buildingUnit"
})
public class PhysicalAddressCType {

    @XmlElement(name = "FamilyName", required = true)
    protected List<FamilyNameSCType> familyName;
    @XmlElement(name = "AddressLine")
    protected String addressLine;
    @XmlElement(name = "Country")
    protected CodelistDataElementCType country;
    @XmlElement(name = "Region")
    protected CodelistDataElementCType region;
    @XmlElement(name = "County")
    protected CodelistDataElementCType county;
    @XmlElement(name = "Municipality")
    protected CodelistDataElementCType municipality;
    @XmlElement(name = "District")
    protected DistrictCType district;
    @XmlElement(name = "StreetName")
    protected String streetName;
    @XmlElement(name = "AdditionalStreetData")
    protected AdditionalStreetDataCType additionalStreetData;
    @XmlElement(name = "BuildingNumber")
    protected String buildingNumber;
    @XmlElement(name = "PropertyRegistrationNumber")
    protected BigInteger propertyRegistrationNumber;
    @XmlElement(name = "AddressPoint")
    protected AddressPointCType addressPoint;
    @XmlElement(name = "BuildingIndex")
    protected String buildingIndex;
    @XmlElement(name = "DeliveryAddress")
    protected DeliveryAddressCType deliveryAddress;
    @XmlElement(name = "Building")
    protected BuildingCType building;
    @XmlElement(name = "AddressType")
    protected AddressTypeCType addressType;
    @XmlElement(name = "BuildingUnit")
    protected List<BuildingUnitSCType> buildingUnit;

    /**
     * Gets the value of the familyName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the familyName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFamilyName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FamilyNameSCType }
     * 
     * 
     */
    public List<FamilyNameSCType> getFamilyName() {
        if (familyName == null) {
            familyName = new ArrayList<FamilyNameSCType>();
        }
        return this.familyName;
    }

    /**
     * Gets the value of the addressLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine() {
        return addressLine;
    }

    /**
     * Sets the value of the addressLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine(String value) {
        this.addressLine = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public CodelistDataElementCType getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public void setCountry(CodelistDataElementCType value) {
        this.country = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public CodelistDataElementCType getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public void setRegion(CodelistDataElementCType value) {
        this.region = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public CodelistDataElementCType getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public void setCounty(CodelistDataElementCType value) {
        this.county = value;
    }

    /**
     * Gets the value of the municipality property.
     * 
     * @return
     *     possible object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public CodelistDataElementCType getMunicipality() {
        return municipality;
    }

    /**
     * Sets the value of the municipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelistDataElementCType }
     *     
     */
    public void setMunicipality(CodelistDataElementCType value) {
        this.municipality = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link DistrictCType }
     *     
     */
    public DistrictCType getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistrictCType }
     *     
     */
    public void setDistrict(DistrictCType value) {
        this.district = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the additionalStreetData property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStreetDataCType }
     *     
     */
    public AdditionalStreetDataCType getAdditionalStreetData() {
        return additionalStreetData;
    }

    /**
     * Sets the value of the additionalStreetData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStreetDataCType }
     *     
     */
    public void setAdditionalStreetData(AdditionalStreetDataCType value) {
        this.additionalStreetData = value;
    }

    /**
     * Gets the value of the buildingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingNumber() {
        return buildingNumber;
    }

    /**
     * Sets the value of the buildingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingNumber(String value) {
        this.buildingNumber = value;
    }

    /**
     * Gets the value of the propertyRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPropertyRegistrationNumber() {
        return propertyRegistrationNumber;
    }

    /**
     * Sets the value of the propertyRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPropertyRegistrationNumber(BigInteger value) {
        this.propertyRegistrationNumber = value;
    }

    /**
     * Gets the value of the addressPoint property.
     * 
     * @return
     *     possible object is
     *     {@link AddressPointCType }
     *     
     */
    public AddressPointCType getAddressPoint() {
        return addressPoint;
    }

    /**
     * Sets the value of the addressPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressPointCType }
     *     
     */
    public void setAddressPoint(AddressPointCType value) {
        this.addressPoint = value;
    }

    /**
     * Gets the value of the buildingIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingIndex() {
        return buildingIndex;
    }

    /**
     * Sets the value of the buildingIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingIndex(String value) {
        this.buildingIndex = value;
    }

    /**
     * Gets the value of the deliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryAddressCType }
     *     
     */
    public DeliveryAddressCType getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * Sets the value of the deliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryAddressCType }
     *     
     */
    public void setDeliveryAddress(DeliveryAddressCType value) {
        this.deliveryAddress = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link BuildingCType }
     *     
     */
    public BuildingCType getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildingCType }
     *     
     */
    public void setBuilding(BuildingCType value) {
        this.building = value;
    }

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link AddressTypeCType }
     *     
     */
    public AddressTypeCType getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressTypeCType }
     *     
     */
    public void setAddressType(AddressTypeCType value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the buildingUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buildingUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuildingUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuildingUnitSCType }
     * 
     * 
     */
    public List<BuildingUnitSCType> getBuildingUnit() {
        if (buildingUnit == null) {
            buildingUnit = new ArrayList<BuildingUnitSCType>();
        }
        return this.buildingUnit;
    }

}
