//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecipientCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecipientCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonName" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}PersonNameCType" minOccurs="0"/&gt;
 *         &lt;element name="AdditionalText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationUnitName" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}OrganizationUnitNameSCType" minOccurs="0"/&gt;
 *         &lt;element name="CorporateBodyFullName" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}CorporateBodyFullNameSCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecipientCType", propOrder = {
    "personName",
    "additionalText",
    "organizationUnitName",
    "corporateBodyFullName"
})
public class RecipientCType {

    @XmlElement(name = "PersonName")
    protected PersonNameCType personName;
    @XmlElement(name = "AdditionalText")
    protected String additionalText;
    @XmlElement(name = "OrganizationUnitName")
    protected OrganizationUnitNameSCType organizationUnitName;
    @XmlElement(name = "CorporateBodyFullName")
    protected CorporateBodyFullNameSCType corporateBodyFullName;

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameCType }
     *     
     */
    public PersonNameCType getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameCType }
     *     
     */
    public void setPersonName(PersonNameCType value) {
        this.personName = value;
    }

    /**
     * Gets the value of the additionalText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalText() {
        return additionalText;
    }

    /**
     * Sets the value of the additionalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalText(String value) {
        this.additionalText = value;
    }

    /**
     * Gets the value of the organizationUnitName property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationUnitNameSCType }
     *     
     */
    public OrganizationUnitNameSCType getOrganizationUnitName() {
        return organizationUnitName;
    }

    /**
     * Sets the value of the organizationUnitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationUnitNameSCType }
     *     
     */
    public void setOrganizationUnitName(OrganizationUnitNameSCType value) {
        this.organizationUnitName = value;
    }

    /**
     * Gets the value of the corporateBodyFullName property.
     * 
     * @return
     *     possible object is
     *     {@link CorporateBodyFullNameSCType }
     *     
     */
    public CorporateBodyFullNameSCType getCorporateBodyFullName() {
        return corporateBodyFullName;
    }

    /**
     * Sets the value of the corporateBodyFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorporateBodyFullNameSCType }
     *     
     */
    public void setCorporateBodyFullName(CorporateBodyFullNameSCType value) {
        this.corporateBodyFullName = value;
    }

}
