//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for resultCodeResponseCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resultCodeResponseCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}baseResponseCType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResultCode" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="ResultReason" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resultCodeResponseCType", propOrder = {
    "resultCode",
    "resultReason"
})
public abstract class ResultCodeResponseCType
    extends BaseResponseCType
{

    @XmlElement(name = "ResultCode")
    protected long resultCode;
    @XmlElement(name = "ResultReason")
    protected List<String> resultReason;

    /**
     * Gets the value of the resultCode property.
     * 
     */
    public long getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     */
    public void setResultCode(long value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getResultReason() {
        if (resultReason == null) {
            resultReason = new ArrayList<String>();
        }
        return this.resultReason;
    }

}
