//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.08.10 at 08:23:59 AM CEST 
//


package sk.is.urso.model.ra;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StreetAxisNodeCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreetAxisNodeCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="XYH" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}XYHCType" minOccurs="0"/&gt;
 *         &lt;element name="BLH" type="{http://www.dominanz.sk/UVZ/Reg/ADDRESS}BLHCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreetAxisNodeCType", propOrder = {
    "xyh",
    "blh"
})
public class StreetAxisNodeCType {

    @XmlElement(name = "XYH")
    protected XYHCType xyh;
    @XmlElement(name = "BLH")
    protected BLHCType blh;

    /**
     * Gets the value of the xyh property.
     * 
     * @return
     *     possible object is
     *     {@link XYHCType }
     *     
     */
    public XYHCType getXYH() {
        return xyh;
    }

    /**
     * Sets the value of the xyh property.
     * 
     * @param value
     *     allowed object is
     *     {@link XYHCType }
     *     
     */
    public void setXYH(XYHCType value) {
        this.xyh = value;
    }

    /**
     * Gets the value of the blh property.
     * 
     * @return
     *     possible object is
     *     {@link BLHCType }
     *     
     */
    public BLHCType getBLH() {
        return blh;
    }

    /**
     * Sets the value of the blh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLHCType }
     *     
     */
    public void setBLH(BLHCType value) {
        this.blh = value;
    }

}
