//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.07 at 10:55:27 AM CET 
//


package sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync;

import sk.is.urso.model.csru.api.async.common.FileListCType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetStatusResponseCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStatusResponseCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="csruTransactionId" type="{http://csru.gov.sk/common/v1.4}CsruTransactionIdType"/&gt;
 *         &lt;element name="ovmTransactionId" type="{http://csru.gov.sk/common/v1.4}OvmTransactionIdType"/&gt;
 *         &lt;element name="ovmCorrelationId" type="{http://csru.gov.sk/common/v1.4}OvmCorrelationIdType"/&gt;
 *         &lt;element name="resultCode" type="{http://csru.gov.sk/common/v1.4}ResultCodeType"/&gt;
 *         &lt;element name="errorMessage" type="{http://csru.gov.sk/common/v1.4}ErrorMessageType" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://csru.gov.sk/common/v1.4}StatusType"/&gt;
 *         &lt;element name="requestProcessingErrorMessage" type="{http://csru.gov.sk/common/v1.4}ErrorMessageType" minOccurs="0"/&gt;
 *         &lt;element name="fileList" type="{http://csru.gov.sk/common/v1.4}FileListCType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStatusResponseCType", propOrder = {
    "csruTransactionId",
    "ovmTransactionId",
    "ovmCorrelationId",
    "resultCode",
    "errorMessage",
    "status",
    "requestProcessingErrorMessage",
    "fileList"
})
public class GetStatusResponseCType {

    @XmlElement(required = true)
    protected String csruTransactionId;
    @XmlElement(required = true)
    protected String ovmTransactionId;
    @XmlElement(required = true)
    protected String ovmCorrelationId;
    @XmlSchemaType(name = "integer")
    protected int resultCode;
    protected String errorMessage;
    protected long status;
    protected String requestProcessingErrorMessage;
    @XmlElement(required = true)
    protected FileListCType fileList;

    /**
     * Gets the value of the csruTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsruTransactionId() {
        return csruTransactionId;
    }

    /**
     * Sets the value of the csruTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsruTransactionId(String value) {
        this.csruTransactionId = value;
    }

    /**
     * Gets the value of the ovmTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmTransactionId() {
        return ovmTransactionId;
    }

    /**
     * Sets the value of the ovmTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmTransactionId(String value) {
        this.ovmTransactionId = value;
    }

    /**
     * Gets the value of the ovmCorrelationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmCorrelationId() {
        return ovmCorrelationId;
    }

    /**
     * Sets the value of the ovmCorrelationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmCorrelationId(String value) {
        this.ovmCorrelationId = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     */
    public int getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     */
    public void setResultCode(int value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public long getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(long value) {
        this.status = value;
    }

    /**
     * Gets the value of the requestProcessingErrorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestProcessingErrorMessage() {
        return requestProcessingErrorMessage;
    }

    /**
     * Sets the value of the requestProcessingErrorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestProcessingErrorMessage(String value) {
        this.requestProcessingErrorMessage = value;
    }

    /**
     * Gets the value of the fileList property.
     * 
     * @return
     *     possible object is
     *     {@link FileListCType }
     *     
     */
    public FileListCType getFileList() {
        return fileList;
    }

    /**
     * Sets the value of the fileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileListCType }
     *     
     */
    public void setFileList(FileListCType value) {
        this.fileList = value;
    }

}
