//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 04:19:13 PM CET 
//


package sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync;

import sk.is.urso.model.csru.api.async.common.DataPlaceholderCType;
import sk.is.urso.model.csru.api.async.common.FileCType;
import sk.is.urso.model.csru.api.async.common.FileListCType;
import sk.is.urso.model.csru.api.async.common.GetProgressRequestCType;
import sk.is.urso.model.csru.api.async.common.GetProgressResponseCType;
import sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetStatusRequestCType;
import sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetStatusResponseCType;
import sk.is.urso.model.csru.api.async.common.ParameterCType;
import sk.is.urso.model.csru.api.async.common.ParameterListCType;
import sk.is.urso.model.csru.api.async.common.ProgressCType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.is.urso.model.csru.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetConsolidatedDataRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetConsolidatedDataRequest");
    private final static QName _GetConsolidatedDataResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetConsolidatedDataResponse");
    private final static QName _GetProgressRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetProgressRequest");
    private final static QName _GetProgressResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetProgressResponse");
    private final static QName _GetStatusRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetStatusRequest");
    private final static QName _GetStatusResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata/v1.4", "GetStatusResponse");
    private final static QName _Base64Content_QNAME = new QName("http://csru.gov.sk/common/v1.4", "base64Content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.is.urso.model.csru.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType }
     * 
     */
    public sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType createGetConsolidatedDataRequestCType() {
        return new sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType();
    }

    /**
     * Create an instance of {@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType }
     * 
     */
    public sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType createGetConsolidatedDataResponseCType() {
        return new sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType();
    }

    /**
     * Create an instance of {@link GetProgressRequestCType }
     * 
     */
    public GetProgressRequestCType createGetProgressRequestCType() {
        return new GetProgressRequestCType();
    }

    /**
     * Create an instance of {@link GetProgressResponseCType }
     * 
     */
    public GetProgressResponseCType createGetProgressResponseCType() {
        return new GetProgressResponseCType();
    }

    /**
     * Create an instance of {@link GetStatusRequestCType }
     * 
     */
    public GetStatusRequestCType createGetStatusRequestCType() {
        return new GetStatusRequestCType();
    }

    /**
     * Create an instance of {@link GetStatusResponseCType }
     * 
     */
    public GetStatusResponseCType createGetStatusResponseCType() {
        return new GetStatusResponseCType();
    }

    /**
     * Create an instance of {@link ProgressCType }
     * 
     */
    public ProgressCType createProgressCType() {
        return new ProgressCType();
    }

    /**
     * Create an instance of {@link ParameterListCType }
     * 
     */
    public ParameterListCType createParameterListCType() {
        return new ParameterListCType();
    }

    /**
     * Create an instance of {@link ParameterCType }
     * 
     */
    public ParameterCType createParameterCType() {
        return new ParameterCType();
    }

    /**
     * Create an instance of {@link DataPlaceholderCType }
     * 
     */
    public DataPlaceholderCType createDataPlaceholderCType() {
        return new DataPlaceholderCType();
    }

    /**
     * Create an instance of {@link FileListCType }
     * 
     */
    public FileListCType createFileListCType() {
        return new FileListCType();
    }

    /**
     * Create an instance of {@link FileCType }
     * 
     */
    public FileCType createFileCType() {
        return new FileCType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetConsolidatedDataRequest")
    public JAXBElement<sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType> createGetConsolidatedDataRequest(sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType value) {
        return new JAXBElement<sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataRequestCType>(_GetConsolidatedDataRequest_QNAME, GetConsolidatedDataRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetConsolidatedDataResponse")
    public JAXBElement<sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType> createGetConsolidatedDataResponse(sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType value) {
        return new JAXBElement<sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync.GetConsolidatedDataResponseCType>(_GetConsolidatedDataResponse_QNAME, GetConsolidatedDataResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProgressRequestCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetProgressRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetProgressRequest")
    public JAXBElement<GetProgressRequestCType> createGetProgressRequest(GetProgressRequestCType value) {
        return new JAXBElement<GetProgressRequestCType>(_GetProgressRequest_QNAME, GetProgressRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProgressResponseCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetProgressResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetProgressResponse")
    public JAXBElement<GetProgressResponseCType> createGetProgressResponse(GetProgressResponseCType value) {
        return new JAXBElement<GetProgressResponseCType>(_GetProgressResponse_QNAME, GetProgressResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusRequestCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatusRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetStatusRequest")
    public JAXBElement<GetStatusRequestCType> createGetStatusRequest(GetStatusRequestCType value) {
        return new JAXBElement<GetStatusRequestCType>(_GetStatusRequest_QNAME, GetStatusRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusResponseCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatusResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", name = "GetStatusResponse")
    public JAXBElement<GetStatusResponseCType> createGetStatusResponse(GetStatusResponseCType value) {
        return new JAXBElement<GetStatusResponseCType>(_GetStatusResponse_QNAME, GetStatusResponseCType.class, null, value);
    }

//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
//     *
//     * @param value
//     *     Java instance representing xml element's value.
//     * @return
//     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
//     */
//    @XmlElementDecl(namespace = "http://csru.gov.sk/common/v1.4", name = "base64Content")
//    public JAXBElement<byte[]> createBase64Content(byte[] value) {
//        return new JAXBElement<byte[]>(_Base64Content_QNAME, byte[].class, null, ((byte[]) value));
//    }

}
