//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 04:19:13 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://csru.gov.sk/csru_getconsolidateddata/v1.4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sk.is.urso.model.csru.api.async.GetConsolidatedDataServiceAsync;
