create schema if not exists csru_set;

create table if not exists csru_set.set_dlznici_refresh
(
    id               integer generated by default as identity
        constraint set_dlznici_refresh_pk
            primary key,
    date_refresh     timestamp default now() not null,
    source           smallint                not null,
    records_modified integer                 not null
);

create table if not exists csru_set.set_dlznici
(
    id           integer generated by default as identity
        constraint set_dlznici_pk
            primary key,
    nazov        varchar not null,
    ico          varchar not null,
    id_po        integer,
    id_refreshed integer
        constraint set_dlznici_refresh_fk
            references csru_set.set_dlznici_refresh
);

create table if not exists csru_set.set_dlznici_obdobie
(
    id         integer generated by default as identity
        constraint set_dlznici_obdobie_pk
            primary key,
    id_dlznici integer not null
        constraint set_dlznici_obdobie_fk
            references csru_set.set_dlznici,
    obdobie_od date,
    obdobie_do date,
    zdroj      smallint
);

alter table csru_set.set_dlznici_obdobie
    add column if not exists typ_dlznika varchar(3);