//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.30 at 01:24:48 PM CET 
//


package sk.is.urso.model.csru.api.sync.GetConsolidatedReferenceDataServiceSync;

import sk.is.urso.model.csru.api.sync.common.DataPlaceholderCType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetConsolidatedReferenceDataResponseCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetConsolidatedReferenceDataResponseCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="csruTransactionId" type="{http://csru.gov.sk/common/v1.4}CsruTransactionIdType"/&gt;
 *         &lt;element name="ovmTransactionId" type="{http://csru.gov.sk/common/v1.4}OvmTransactionIdType"/&gt;
 *         &lt;element name="ovmCorrelationId" type="{http://csru.gov.sk/common/v1.4}OvmCorrelationIdType"/&gt;
 *         &lt;element name="resultCode" type="{http://csru.gov.sk/common/v1.4}ResultCodeType"/&gt;
 *         &lt;element name="errorMessage" type="{http://csru.gov.sk/common/v1.4}ErrorMessageType" minOccurs="0"/&gt;
 *         &lt;element name="payload" type="{http://csru.gov.sk/common/v1.4}DataPlaceholderCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetConsolidatedReferenceDataResponseCType", namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata_sync/v1.4", propOrder = {
    "csruTransactionId",
    "ovmTransactionId",
    "ovmCorrelationId",
    "resultCode",
    "errorMessage",
    "payload"
})
public class GetConsolidatedReferenceDataResponseCType {

    @XmlElement(required = true)
    protected String csruTransactionId;
    @XmlElement(required = true)
    protected String ovmTransactionId;
    @XmlElement(required = true)
    protected String ovmCorrelationId;
    @XmlSchemaType(name = "integer")
    protected int resultCode;
    protected String errorMessage;
    protected DataPlaceholderCType payload;

    /**
     * Gets the value of the csruTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsruTransactionId() {
        return csruTransactionId;
    }

    /**
     * Sets the value of the csruTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsruTransactionId(String value) {
        this.csruTransactionId = value;
    }

    /**
     * Gets the value of the ovmTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmTransactionId() {
        return ovmTransactionId;
    }

    /**
     * Sets the value of the ovmTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmTransactionId(String value) {
        this.ovmTransactionId = value;
    }

    /**
     * Gets the value of the ovmCorrelationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmCorrelationId() {
        return ovmCorrelationId;
    }

    /**
     * Sets the value of the ovmCorrelationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmCorrelationId(String value) {
        this.ovmCorrelationId = value;
    }

    /**
     * Gets the value of the resultCode property.
     * 
     */
    public int getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     */
    public void setResultCode(int value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link DataPlaceholderCType }
     *     
     */
    public DataPlaceholderCType getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPlaceholderCType }
     *     
     */
    public void setPayload(DataPlaceholderCType value) {
        this.payload = value;
    }

}
