//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.30 at 01:24:48 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://csru.gov.sk/common/v1.4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sk.is.urso.model.csru.api.sync.GetConsolidatedReferenceDataServiceSync;
