//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.30 at 01:19:25 PM CET 
//


package sk.is.urso.model.csru.api.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProviderStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProviderStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PROCESSING"/&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="ERROR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProviderStatus", namespace = "http://csru.gov.sk/common/v1.4")
@XmlEnum
public enum ProviderStatus {


    /**
     * Prebieha spracovanie
     * 
     */
    PROCESSING,

    /**
     * Spracovanie úspešne ukončené
     * 
     */
    OK,

    /**
     * Spracovanie ukončené s chybou
     * 
     */
    ERROR;

    public String value() {
        return name();
    }

    public static ProviderStatus fromValue(String v) {
        return valueOf(v);
    }

}
