//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 01:05:55 PM CEST 
//


package sk.is.urso.model.fo;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Vstupné XML WS.
 *
 * <p>Java class for TPOD complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TPOD"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IOSList" type="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TIOSList"/&gt;
 *         &lt;element name="UES" type="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TUES"/&gt;
 *         &lt;element name="SPIList" type="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TSPI_SPNList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPOD", propOrder = {
        "iosList",
        "ues",
        "spiList"
})
public class TPOD implements ToString2 {

    @XmlElement(name = "IOSList", required = true)
    protected TIOSList iosList;
    @XmlElement(name = "UES", required = true)
    protected TUES ues;
    @XmlElement(name = "SPIList", required = true)
    protected TSPISPNList spiList;

    /**
     * Gets the value of the iosList property.
     *
     * @return possible object is
     * {@link TIOSList }
     */
    public TIOSList getIOSList() {
        return iosList;
    }

    /**
     * Sets the value of the iosList property.
     *
     * @param value allowed object is
     *              {@link TIOSList }
     */
    public void setIOSList(TIOSList value) {
        this.iosList = value;
    }

    /**
     * Gets the value of the ues property.
     *
     * @return possible object is
     * {@link TUES }
     */
    public TUES getUES() {
        return ues;
    }

    /**
     * Sets the value of the ues property.
     *
     * @param value allowed object is
     *              {@link TUES }
     */
    public void setUES(TUES value) {
        this.ues = value;
    }

    /**
     * Gets the value of the spiList property.
     *
     * @return possible object is
     * {@link TSPISPNList }
     */
    public TSPISPNList getSPIList() {
        return spiList;
    }

    /**
     * Sets the value of the spiList property.
     *
     * @param value allowed object is
     *              {@link TSPISPNList }
     */
    public void setSPIList(TSPISPNList value) {
        this.spiList = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            TIOSList theIOSList;
            theIOSList = this.getIOSList();
            strategy.appendField(locator, this, "iosList", buffer, theIOSList, (this.iosList != null));
        }
        {
            TUES theUES;
            theUES = this.getUES();
            strategy.appendField(locator, this, "ues", buffer, theUES, (this.ues != null));
        }
        {
            TSPISPNList theSPIList;
            theSPIList = this.getSPIList();
            strategy.appendField(locator, this, "spiList", buffer, theSPIList, (this.spiList != null));
        }
        return buffer;
    }

}
