//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 01:05:55 PM CEST 
//


package sk.is.urso.model.fo;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Výstupné XML WS.
 *
 * <p>Java class for TPOVO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TPOVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NU" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="512"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="KO" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="AC" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="OEXList" type="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TOEX_OEIOList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPOVO", propOrder = {
        "nu",
        "ko",
        "ac",
        "oexList"
})
public class TPOVO implements ToString2 {

    @XmlElement(name = "NU")
    protected String nu;
    @XmlElement(name = "KO")
    protected int ko;
    @XmlElement(name = "AC", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ac;
    @XmlElement(name = "OEXList", required = true)
    protected TOEXOEIOList oexList;

    /**
     * Gets the value of the nu property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNU() {
        return nu;
    }

    /**
     * Sets the value of the nu property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNU(String value) {
        this.nu = value;
    }

    /**
     * Gets the value of the ko property.
     */
    public int getKO() {
        return ko;
    }

    /**
     * Sets the value of the ko property.
     */
    public void setKO(int value) {
        this.ko = value;
    }

    /**
     * Gets the value of the ac property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getAC() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setAC(XMLGregorianCalendar value) {
        this.ac = value;
    }

    /**
     * Gets the value of the oexList property.
     *
     * @return possible object is
     * {@link TOEXOEIOList }
     */
    public TOEXOEIOList getOEXList() {
        return oexList;
    }

    /**
     * Sets the value of the oexList property.
     *
     * @param value allowed object is
     *              {@link TOEXOEIOList }
     */
    public void setOEXList(TOEXOEIOList value) {
        this.oexList = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theNU;
            theNU = this.getNU();
            strategy.appendField(locator, this, "nu", buffer, theNU, (this.nu != null));
        }
        {
            int theKO;
            theKO = this.getKO();
            strategy.appendField(locator, this, "ko", buffer, theKO, true);
        }
        {
            XMLGregorianCalendar theAC;
            theAC = this.getAC();
            strategy.appendField(locator, this, "ac", buffer, theAC, (this.ac != null));
        }
        {
            TOEXOEIOList theOEXList;
            theOEXList = this.getOEXList();
            strategy.appendField(locator, this, "oexList", buffer, theOEXList, (this.oexList != null));
        }
        return buffer;
    }

}
