//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 01:05:55 PM CEST 
//


package sk.is.urso.model.fo;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransEnvTypeOut complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TransEnvTypeOut"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TransEnvelopeType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="POV" type="{http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd}TPOVO"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="corrID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransEnvTypeOut", propOrder = {
        "pov"
})
public class TransEnvTypeOut
        extends TransEnvelopeType
        implements ToString2 {

    @XmlElement(name = "POV", required = true)
    protected TPOVO pov;
    @XmlAttribute(name = "corrID")
    protected String corrID;

    /**
     * Gets the value of the pov property.
     *
     * @return possible object is
     * {@link TPOVO }
     */
    public TPOVO getPOV() {
        return pov;
    }

    /**
     * Sets the value of the pov property.
     *
     * @param value allowed object is
     *              {@link TPOVO }
     */
    public void setPOV(TPOVO value) {
        this.pov = value;
    }

    /**
     * Gets the value of the corrID property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCorrID() {
        return corrID;
    }

    /**
     * Sets the value of the corrID property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCorrID(String value) {
        this.corrID = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            TPOVO thePOV;
            thePOV = this.getPOV();
            strategy.appendField(locator, this, "pov", buffer, thePOV, (this.pov != null));
        }
        {
            String theCorrID;
            theCorrID = this.getCorrID();
            strategy.appendField(locator, this, "corrID", buffer, theCorrID, (this.corrID != null));
        }
        return buffer;
    }

}
