//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 01:05:55 PM CEST 
//


package sk.is.urso.model.fo;

import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Špecifikuje požadovaný typ informácie na výstupe.
 *
 * <p>Java class for TSPI_SPN complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TSPI_SPN"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TUDHONA"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="100"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HO" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSPI_SPN", propOrder = {
        "tudhona",
        "ho"
})
public class TSPISPN implements ToString2 {

    @XmlElement(name = "TUDHONA", required = true)
    protected String tudhona;
    @XmlElement(name = "HO")
    protected int ho;

    /**
     * Gets the value of the tudhona property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTUDHONA() {
        return tudhona;
    }

    /**
     * Sets the value of the tudhona property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTUDHONA(String value) {
        this.tudhona = value;
    }

    /**
     * Gets the value of the ho property.
     */
    public int getHO() {
        return ho;
    }

    /**
     * Sets the value of the ho property.
     */
    public void setHO(int value) {
        this.ho = value;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            String theTUDHONA;
            theTUDHONA = this.getTUDHONA();
            strategy.appendField(locator, this, "tudhona", buffer, theTUDHONA, (this.tudhona != null));
        }
        {
            int theHO;
            theHO = this.getHO();
            strategy.appendField(locator, this, "ho", buffer, theHO, true);
        }
        return buffer;
    }

}
