//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.25 at 02:24:29 PM CET 
//


package sk.is.urso.model.csru.api.async.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetReferenceDataRequestCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetReferenceDataRequestCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ovmIsId" type="{http://csru.gov.sk/common/v1.4}OvmIsIdType"/&gt;
 *         &lt;element name="oeId" type="{http://csru.gov.sk/common/v1.4}OeIdType"/&gt;
 *         &lt;element name="scenario" type="{http://csru.gov.sk/common/v1.4}ScenarioType"/&gt;
 *         &lt;element name="ovmTransactionId" type="{http://csru.gov.sk/common/v1.4}OvmTransactionIdType"/&gt;
 *         &lt;element name="ovmCorrelationId" type="{http://csru.gov.sk/common/v1.4}OvmCorrelationIdType"/&gt;
 *         &lt;element name="payload" type="{http://csru.gov.sk/common/v1.4}DataPlaceholderCType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetReferenceDataRequestCType", propOrder = {
    "ovmIsId",
    "oeId",
    "scenario",
    "ovmTransactionId",
    "ovmCorrelationId",
    "payload"
})
public class GetReferenceDataRequestCType {

    @XmlElement(required = true)
    protected String ovmIsId;
    @XmlElement(required = true)
    protected String oeId;
    @XmlElement(required = true)
    protected String scenario;
    @XmlElement(required = true)
    protected String ovmTransactionId;
    @XmlElement(required = true)
    protected String ovmCorrelationId;
    @XmlElement(required = true)
    protected sk.is.urso.model.csru.api.async.common.DataPlaceholderCType payload;

    /**
     * Gets the value of the ovmIsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmIsId() {
        return ovmIsId;
    }

    /**
     * Sets the value of the ovmIsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmIsId(String value) {
        this.ovmIsId = value;
    }

    /**
     * Gets the value of the oeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOeId() {
        return oeId;
    }

    /**
     * Sets the value of the oeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOeId(String value) {
        this.oeId = value;
    }

    /**
     * Gets the value of the scenario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * Sets the value of the scenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenario(String value) {
        this.scenario = value;
    }

    /**
     * Gets the value of the ovmTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmTransactionId() {
        return ovmTransactionId;
    }

    /**
     * Sets the value of the ovmTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmTransactionId(String value) {
        this.ovmTransactionId = value;
    }

    /**
     * Gets the value of the ovmCorrelationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmCorrelationId() {
        return ovmCorrelationId;
    }

    /**
     * Sets the value of the ovmCorrelationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmCorrelationId(String value) {
        this.ovmCorrelationId = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link sk.is.urso.model.csru.api.async.common.DataPlaceholderCType }
     *     
     */
    public sk.is.urso.model.csru.api.async.common.DataPlaceholderCType getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link sk.is.urso.model.csru.api.async.common.DataPlaceholderCType }
     *     
     */
    public void setPayload(DataPlaceholderCType value) {
        this.payload = value;
    }

}
