//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.07 at 10:55:27 AM CET 
//


package sk.is.urso.model.csru.api.async.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetStatusRequestCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetStatusRequestCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ovmIsId" type="{http://csru.gov.sk/common/v1.4}OvmIsIdType"/&gt;
 *         &lt;element name="requestId" type="{http://csru.gov.sk/common/v1.4}RequestIdType"/&gt;
 *         &lt;element name="ovmTransactionId" type="{http://csru.gov.sk/common/v1.4}OvmTransactionIdType"/&gt;
 *         &lt;element name="ovmCorrelationId" type="{http://csru.gov.sk/common/v1.4}OvmCorrelationIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetStatusRequestCType", propOrder = {
    "ovmIsId",
    "requestId",
    "ovmTransactionId",
    "ovmCorrelationId"
})
public class GetStatusRequestCType {

    @XmlElement(required = true)
    protected String ovmIsId;
    protected long requestId;
    @XmlElement(required = true)
    protected String ovmTransactionId;
    @XmlElement(required = true)
    protected String ovmCorrelationId;

    /**
     * Gets the value of the ovmIsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmIsId() {
        return ovmIsId;
    }

    /**
     * Sets the value of the ovmIsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmIsId(String value) {
        this.ovmIsId = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     */
    public long getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     */
    public void setRequestId(long value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the ovmTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmTransactionId() {
        return ovmTransactionId;
    }

    /**
     * Sets the value of the ovmTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmTransactionId(String value) {
        this.ovmTransactionId = value;
    }

    /**
     * Gets the value of the ovmCorrelationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvmCorrelationId() {
        return ovmCorrelationId;
    }

    /**
     * Sets the value of the ovmCorrelationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvmCorrelationId(String value) {
        this.ovmCorrelationId = value;
    }

}
