//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.07 at 10:55:27 AM CET 
//


package sk.is.urso.model.csru.api.async.common;

import sk.is.urso.model.csru.api.async.GetChangedReferenceDataServiceAsync.GetChangedReferenceDataRequestCType;
import sk.is.urso.model.csru.api.async.GetChangedReferenceDataServiceAsync.GetChangedReferenceDataResponseCType;
import sk.is.urso.model.csru.api.async.GetReferenceDataByIdentifiersServiceAsync.GetReferenceDataByIdentifiersRequestCType;
import sk.is.urso.model.csru.api.async.GetReferenceDataByIdentifiersServiceAsync.GetReferenceDataByIdentifiersResponseCType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the sk.is.urso.model.csru.test package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetReferenceDataRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetReferenceDataRequest");
    private final static QName _GetReferenceDataResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetReferenceDataResponse");
    private final static QName _GetReferenceDataByIdentifiersRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetReferenceDataByIdentifiersRequest");
    private final static QName _GetReferenceDataByIdentifiersResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetReferenceDataByIdentifiersResponse");
    private final static QName _GetStatusRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetStatusRequest");
    private final static QName _GetStatusResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetStatusResponse");
    private final static QName _GetChangedReferenceDataRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetChangedReferenceDataRequest");
    private final static QName _GetChangedReferenceDataResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", "GetChangedReferenceDataResponse");
    private final static QName _Base64Content_QNAME = new QName("http://csru.gov.sk/common/v1.4", "base64Content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.is.urso.model.csru.test
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetReferenceDataRequestCType }
     *
     */
    public GetReferenceDataRequestCType createGetReferenceDataRequestCType() {
        return new GetReferenceDataRequestCType();
    }

    /**
     * Create an instance of {@link GetReferenceDataResponseCType }
     *
     */
    public GetReferenceDataResponseCType createGetReferenceDataResponseCType() {
        return new GetReferenceDataResponseCType();
    }

    /**
     * Create an instance of {@link GetReferenceDataByIdentifiersRequestCType }
     *
     */
    public GetReferenceDataByIdentifiersRequestCType createGetReferenceDataByIdentifiersRequestCType() {
        return new GetReferenceDataByIdentifiersRequestCType();
    }

    /**
     * Create an instance of {@link GetReferenceDataByIdentifiersResponseCType }
     *
     */
    public GetReferenceDataByIdentifiersResponseCType createGetReferenceDataByIdentifiersResponseCType() {
        return new GetReferenceDataByIdentifiersResponseCType();
    }

    /**
     * Create an instance of {@link GetStatusRequestCType }
     *
     */
    public GetStatusRequestCType createGetStatusRequestCType() {
        return new GetStatusRequestCType();
    }

    /**
     * Create an instance of {@link GetStatusResponseCType }
     *
     */
    public GetStatusResponseCType createGetStatusResponseCType() {
        return new GetStatusResponseCType();
    }

    /**
     * Create an instance of {@link GetChangedReferenceDataRequestCType }
     *
     */
    public GetChangedReferenceDataRequestCType createGetChangedReferenceDataRequestCType() {
        return new GetChangedReferenceDataRequestCType();
    }

    /**
     * Create an instance of {@link GetChangedReferenceDataResponseCType }
     *
     */
    public GetChangedReferenceDataResponseCType createGetChangedReferenceDataResponseCType() {
        return new GetChangedReferenceDataResponseCType();
    }

    /**
     * Create an instance of {@link ParameterListCType }
     *
     */
    public ParameterListCType createParameterListCType() {
        return new ParameterListCType();
    }

    /**
     * Create an instance of {@link ParameterCType }
     *
     */
    public ParameterCType createParameterCType() {
        return new ParameterCType();
    }

    /**
     * Create an instance of {@link DataPlaceholderCType }
     *
     */
    public DataPlaceholderCType createDataPlaceholderCType() {
        return new DataPlaceholderCType();
    }

    /**
     * Create an instance of {@link FileListCType }
     *
     */
    public FileListCType createFileListCType() {
        return new FileListCType();
    }

    /**
     * Create an instance of {@link FileCType }
     *
     */
    public FileCType createFileCType() {
        return new FileCType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReferenceDataRequestCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReferenceDataRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetReferenceDataRequest")
    public JAXBElement<GetReferenceDataRequestCType> createGetReferenceDataRequest(GetReferenceDataRequestCType value) {
        return new JAXBElement<GetReferenceDataRequestCType>(_GetReferenceDataRequest_QNAME, GetReferenceDataRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReferenceDataResponseCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReferenceDataResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetReferenceDataResponse")
    public JAXBElement<GetReferenceDataResponseCType> createGetReferenceDataResponse(GetReferenceDataResponseCType value) {
        return new JAXBElement<GetReferenceDataResponseCType>(_GetReferenceDataResponse_QNAME, GetReferenceDataResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReferenceDataByIdentifiersRequestCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReferenceDataByIdentifiersRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetReferenceDataByIdentifiersRequest")
    public JAXBElement<GetReferenceDataByIdentifiersRequestCType> createGetReferenceDataByIdentifiersRequest(GetReferenceDataByIdentifiersRequestCType value) {
        return new JAXBElement<GetReferenceDataByIdentifiersRequestCType>(_GetReferenceDataByIdentifiersRequest_QNAME, GetReferenceDataByIdentifiersRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReferenceDataByIdentifiersResponseCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetReferenceDataByIdentifiersResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetReferenceDataByIdentifiersResponse")
    public JAXBElement<GetReferenceDataByIdentifiersResponseCType> createGetReferenceDataByIdentifiersResponse(GetReferenceDataByIdentifiersResponseCType value) {
        return new JAXBElement<GetReferenceDataByIdentifiersResponseCType>(_GetReferenceDataByIdentifiersResponse_QNAME, GetReferenceDataByIdentifiersResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusRequestCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatusRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetStatusRequest")
    public JAXBElement<GetStatusRequestCType> createGetStatusRequest(GetStatusRequestCType value) {
        return new JAXBElement<GetStatusRequestCType>(_GetStatusRequest_QNAME, GetStatusRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatusResponseCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStatusResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetStatusResponse")
    public JAXBElement<GetStatusResponseCType> createGetStatusResponse(GetStatusResponseCType value) {
        return new JAXBElement<GetStatusResponseCType>(_GetStatusResponse_QNAME, GetStatusResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetChangedReferenceDataRequestCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetChangedReferenceDataRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetChangedReferenceDataRequest")
    public JAXBElement<GetChangedReferenceDataRequestCType> createGetChangedReferenceDataRequest(GetChangedReferenceDataRequestCType value) {
        return new JAXBElement<GetChangedReferenceDataRequestCType>(_GetChangedReferenceDataRequest_QNAME, GetChangedReferenceDataRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetChangedReferenceDataResponseCType }{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetChangedReferenceDataResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidatedreferencedata/v1.4", name = "GetChangedReferenceDataResponse")
    public JAXBElement<GetChangedReferenceDataResponseCType> createGetChangedReferenceDataResponse(GetChangedReferenceDataResponseCType value) {
        return new JAXBElement<GetChangedReferenceDataResponseCType>(_GetChangedReferenceDataResponse_QNAME, GetChangedReferenceDataResponseCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     *
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/common/v1.4", name = "base64Content")
    public JAXBElement<byte[]> createBase64Content(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Content_QNAME, byte[].class, null, ((byte[]) value));
    }

}
