//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.07 at 10:55:27 AM CET 
//


package sk.is.urso.model.csru.api.async.common;

import sk.is.urso.model.csru.api.common.ProviderStatus;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProgressCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProgressCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="providerStatus" type="{http://csru.gov.sk/common/v1.4}ProviderStatus"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="oeId" type="{http://csru.gov.sk/common/v1.4}OeIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgressCType", propOrder = {
    "providerStatus",
    "date",
    "oeId"
})
public class ProgressCType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ProviderStatus providerStatus;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String oeId;

    /**
     * Gets the value of the providerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ProviderStatus }
     *     
     */
    public ProviderStatus getProviderStatus() {
        return providerStatus;
    }

    /**
     * Sets the value of the providerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProviderStatus }
     *     
     */
    public void setProviderStatus(ProviderStatus value) {
        this.providerStatus = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the oeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOeId() {
        return oeId;
    }

    /**
     * Sets the value of the oeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOeId(String value) {
        this.oeId = value;
    }

}
