//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.12 at 01:05:55 PM CEST 
//


package sk.is.urso.model.subject.detailIfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.uvzsr.is.reg.csru.fo.detailIfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TransEnvIn_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "TransEnvIn");
    private final static QName _TransEnvOut_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "TransEnvOut");
    private final static QName _TPOBPHROIA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "IA");
    private final static QName _TPOBPHROVD_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "VD");
    private final static QName _TPOBPHRODI_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DI");
    private final static QName _TPOBPHROUI_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UI");
    private final static QName _TPOBPHROCE_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "CE");
    private final static QName _TPOBPHROOA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "OA");
    private final static QName _TPOBPHROUE_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UE");
    private final static QName _TRVERVXOSM_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "SM");
    private final static QName _TRVERVXOPA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "PA");
    private final static QName _TOEXOEIOID_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "ID");
    private final static QName _TOEXOEIOPO_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "PO");
    private final static QName _TOEXOEIORC_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "RC");
    private final static QName _TOEXOEIODN_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DN");
    private final static QName _TOEXOEIOUC_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UC");
    private final static QName _TOEXOEIOUCEUCNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UCEUCNA");
    private final static QName _TOEXOEIOMN_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "MN");
    private final static QName _TOEXOEIOSN_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "SN");
    private final static QName _TOEXOEIOSTASNNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "STASNNA");
    private final static QName _TOEXOEIOPI_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "PI");
    private final static QName _TOEXOEIOPOHPINA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "POHPINA");
    private final static QName _TOEXOEIORS_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "RS");
    private final static QName _TOEXOEIORSTRSNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "RSTRSNA");
    private final static QName _TOEXOEIORM_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "RM");
    private final static QName _TOEXOEIONI_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "NI");
    private final static QName _TOEXOEIONARNINA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "NARNINA");
    private final static QName _TOEXOEIODU_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DU");
    private final static QName _TOEXOEIOUCEUENA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UCEUENA");
    private final static QName _TOEXOEIOMU_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "MU");
    private final static QName _TOEXOEIOUM_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UM");
    private final static QName _TOEXOEIOSU_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "SU");
    private final static QName _TOEXOEIOSTASUNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "STASUNA");
    private final static QName _TOEXOEIOBI_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "BI");
    private final static QName _TOEXOEIOTV_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "TV");
    private final static QName _TOEXOEIOTVKTVNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "TVKTVNA");
    private final static QName _TOEXOEIOUL_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UL");
    private final static QName _TOEXOEIOUCEULNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UCEULNA");
    private final static QName _TOEXOEIOUO_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UO");
    private final static QName _TOEXOEIOUCEUONA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "UCEUONA");
    private final static QName _TOEXOEIOIC_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "IC");
    private final static QName _TOEXOEIOSZ_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "SZ");
    private final static QName _TOEXOEIOSZVSZNA_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "SZVSZNA");
    private final static QName _TOEXOEIORN_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "RN");
    private final static QName _TOEXOEIODK_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DK");
    private final static QName _TOEXOEIODL_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DL");
    private final static QName _TOEXOEIODP_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "DP");
    private final static QName _TOEXOEIOPG_QNAME = new QName("http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", "PG");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.uvzsr.is.reg.csru.fo.detailIfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransEnvTypeIn }
     * 
     */
    public TransEnvTypeIn createTransEnvTypeIn() {
        return new TransEnvTypeIn();
    }

    /**
     * Create an instance of {@link TransEnvTypeOut }
     * 
     */
    public TransEnvTypeOut createTransEnvTypeOut() {
        return new TransEnvTypeOut();
    }

    /**
     * Create an instance of {@link TPOD }
     * 
     */
    public TPOD createTPOD() {
        return new TPOD();
    }

    /**
     * Create an instance of {@link TIOSList }
     * 
     */
    public TIOSList createTIOSList() {
        return new TIOSList();
    }

    /**
     * Create an instance of {@link TIOS }
     * 
     */
    public TIOS createTIOS() {
        return new TIOS();
    }

    /**
     * Create an instance of {@link TUES }
     * 
     */
    public TUES createTUES() {
        return new TUES();
    }

    /**
     * Create an instance of {@link TSPISPNList }
     * 
     */
    public TSPISPNList createTSPISPNList() {
        return new TSPISPNList();
    }

    /**
     * Create an instance of {@link TSPISPN }
     * 
     */
    public TSPISPN createTSPISPN() {
        return new TSPISPN();
    }

    /**
     * Create an instance of {@link TPOVO }
     * 
     */
    public TPOVO createTPOVO() {
        return new TPOVO();
    }

    /**
     * Create an instance of {@link TOEXOEIOList }
     * 
     */
    public TOEXOEIOList createTOEXOEIOList() {
        return new TOEXOEIOList();
    }

    /**
     * Create an instance of {@link TOEXOEIO }
     * 
     */
    public TOEXOEIO createTOEXOEIO() {
        return new TOEXOEIO();
    }

    /**
     * Create an instance of {@link TMOSOList }
     * 
     */
    public TMOSOList createTMOSOList() {
        return new TMOSOList();
    }

    /**
     * Create an instance of {@link TMOSO }
     * 
     */
    public TMOSO createTMOSO() {
        return new TMOSO();
    }

    /**
     * Create an instance of {@link TPRIOList }
     * 
     */
    public TPRIOList createTPRIOList() {
        return new TPRIOList();
    }

    /**
     * Create an instance of {@link TPRIO }
     * 
     */
    public TPRIO createTPRIO() {
        return new TPRIO();
    }

    /**
     * Create an instance of {@link TRPROList }
     * 
     */
    public TRPROList createTRPROList() {
        return new TRPROList();
    }

    /**
     * Create an instance of {@link TRPRO }
     * 
     */
    public TRPRO createTRPRO() {
        return new TRPRO();
    }

    /**
     * Create an instance of {@link TTOSTOIOList }
     * 
     */
    public TTOSTOIOList createTTOSTOIOList() {
        return new TTOSTOIOList();
    }

    /**
     * Create an instance of {@link TTOSTOIO }
     * 
     */
    public TTOSTOIO createTTOSTOIO() {
        return new TTOSTOIO();
    }

    /**
     * Create an instance of {@link TSPRSPIOList }
     * 
     */
    public TSPRSPIOList createTSPRSPIOList() {
        return new TSPRSPIOList();
    }

    /**
     * Create an instance of {@link TSPRSPIO }
     * 
     */
    public TSPRSPIO createTSPRSPIO() {
        return new TSPRSPIO();
    }

    /**
     * Create an instance of {@link TRVERVXOList }
     * 
     */
    public TRVERVXOList createTRVERVXOList() {
        return new TRVERVXOList();
    }

    /**
     * Create an instance of {@link TRVERVXO }
     * 
     */
    public TRVERVXO createTRVERVXO() {
        return new TRVERVXO();
    }

    /**
     * Create an instance of {@link TPOBPHROList }
     * 
     */
    public TPOBPHROList createTPOBPHROList() {
        return new TPOBPHROList();
    }

    /**
     * Create an instance of {@link TPOBPHRO }
     * 
     */
    public TPOBPHRO createTPOBPHRO() {
        return new TPOBPHRO();
    }

    /**
     * Create an instance of {@link TREGOList }
     * 
     */
    public TREGOList createTREGOList() {
        return new TREGOList();
    }

    /**
     * Create an instance of {@link TREGO }
     * 
     */
    public TREGO createTREGO() {
        return new TREGO();
    }

    /**
     * Create an instance of {@link TZPOOList }
     * 
     */
    public TZPOOList createTZPOOList() {
        return new TZPOOList();
    }

    /**
     * Create an instance of {@link TZPOO }
     * 
     */
    public TZPOO createTZPOO() {
        return new TZPOO();
    }

    /**
     * Create an instance of {@link TZPZOList }
     * 
     */
    public TZPZOList createTZPZOList() {
        return new TZPZOList();
    }

    /**
     * Create an instance of {@link TZPZO }
     * 
     */
    public TZPZO createTZPZO() {
        return new TZPZO();
    }

    /**
     * Create an instance of {@link TPZMOList }
     * 
     */
    public TPZMOList createTPZMOList() {
        return new TPZMOList();
    }

    /**
     * Create an instance of {@link TPZMO }
     * 
     */
    public TPZMO createTPZMO() {
        return new TPZMO();
    }

    /**
     * Create an instance of {@link TDCDDCIOList }
     * 
     */
    public TDCDDCIOList createTDCDDCIOList() {
        return new TDCDDCIOList();
    }

    /**
     * Create an instance of {@link TDCDDCIO }
     * 
     */
    public TDCDDCIO createTDCDDCIO() {
        return new TDCDDCIO();
    }

    /**
     * Create an instance of {@link TUSOOList }
     * 
     */
    public TUSOOList createTUSOOList() {
        return new TUSOOList();
    }

    /**
     * Create an instance of {@link TUSOO }
     * 
     */
    public TUSOO createTUSOO() {
        return new TUSOO();
    }

    /**
     * Create an instance of {@link TSNRSNPOList }
     * 
     */
    public TSNRSNPOList createTSNRSNPOList() {
        return new TSNRSNPOList();
    }

    /**
     * Create an instance of {@link TSNRSNPO }
     * 
     */
    public TSNRSNPO createTSNRSNPO() {
        return new TSNRSNPO();
    }

    /**
     * Create an instance of {@link TZUDZUNOList }
     * 
     */
    public TZUDZUNOList createTZUDZUNOList() {
        return new TZUDZUNOList();
    }

    /**
     * Create an instance of {@link TZUDZUNO }
     * 
     */
    public TZUDZUNO createTZUDZUNO() {
        return new TZUDZUNO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransEnvTypeIn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransEnvTypeIn }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "TransEnvIn")
    public JAXBElement<TransEnvTypeIn> createTransEnvIn(TransEnvTypeIn value) {
        return new JAXBElement<TransEnvTypeIn>(_TransEnvIn_QNAME, TransEnvTypeIn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransEnvTypeOut }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransEnvTypeOut }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "TransEnvOut")
    public JAXBElement<TransEnvTypeOut> createTransEnvOut(TransEnvTypeOut value) {
        return new JAXBElement<TransEnvTypeOut>(_TransEnvOut_QNAME, TransEnvTypeOut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "IA", scope = TPOBPHRO.class)
    public JAXBElement<String> createTPOBPHROIA(String value) {
        return new JAXBElement<String>(_TPOBPHROIA_QNAME, String.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "VD", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHROVD(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROVD_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DI", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHRODI(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHRODI_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UI", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHROUI(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROUI_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "CE", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHROCE(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROCE_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "OA", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHROOA(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROOA_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UE", scope = TPOBPHRO.class)
    public JAXBElement<Integer> createTPOBPHROUE(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROUE_QNAME, Integer.class, TPOBPHRO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "SM", scope = TRVERVXO.class)
    public JAXBElement<String> createTRVERVXOSM(String value) {
        return new JAXBElement<String>(_TRVERVXOSM_QNAME, String.class, TRVERVXO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "PA", scope = TRVERVXO.class)
    public JAXBElement<Integer> createTRVERVXOPA(Integer value) {
        return new JAXBElement<Integer>(_TRVERVXOPA_QNAME, Integer.class, TRVERVXO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "ID", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOID(String value) {
        return new JAXBElement<String>(_TOEXOEIOID_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "PO", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOPO(String value) {
        return new JAXBElement<String>(_TOEXOEIOPO_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "RC", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIORC(String value) {
        return new JAXBElement<String>(_TOEXOEIORC_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DN", scope = TOEXOEIO.class)
    public JAXBElement<XMLGregorianCalendar> createTOEXOEIODN(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TOEXOEIODN_QNAME, XMLGregorianCalendar.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UC", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOUC(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOUC_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UCEUCNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOUCEUCNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOUCEUCNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "MN", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOMN(String value) {
        return new JAXBElement<String>(_TOEXOEIOMN_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "SN", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOSN(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOSN_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "STASNNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOSTASNNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOSTASNNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "PI", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOPI(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOPI_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "POHPINA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOPOHPINA(String value) {
        return new JAXBElement<String>(_TOEXOEIOPOHPINA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "RS", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIORS(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIORS_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "RSTRSNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIORSTRSNA(String value) {
        return new JAXBElement<String>(_TOEXOEIORSTRSNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "RM", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIORM(String value) {
        return new JAXBElement<String>(_TOEXOEIORM_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "NI", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIONI(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIONI_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "NARNINA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIONARNINA(String value) {
        return new JAXBElement<String>(_TOEXOEIONARNINA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DU", scope = TOEXOEIO.class)
    public JAXBElement<XMLGregorianCalendar> createTOEXOEIODU(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TOEXOEIODU_QNAME, XMLGregorianCalendar.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UE", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOUE(Integer value) {
        return new JAXBElement<Integer>(_TPOBPHROUE_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UCEUENA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOUCEUENA(String value) {
        return new JAXBElement<String>(_TOEXOEIOUCEUENA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "MU", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOMU(String value) {
        return new JAXBElement<String>(_TOEXOEIOMU_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UM", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOUM(String value) {
        return new JAXBElement<String>(_TOEXOEIOUM_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "SU", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOSU(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOSU_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "STASUNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOSTASUNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOSTASUNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "BI", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOBI(String value) {
        return new JAXBElement<String>(_TOEXOEIOBI_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "TV", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOTV(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOTV_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "TVKTVNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOTVKTVNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOTVKTVNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UL", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOUL(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOUL_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UCEULNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOUCEULNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOUCEULNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UO", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOUO(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOUO_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "UCEUONA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOUCEUONA(String value) {
        return new JAXBElement<String>(_TOEXOEIOUCEUONA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "IC", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOIC(String value) {
        return new JAXBElement<String>(_TOEXOEIOIC_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "SZ", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOSZ(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOSZ_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "SZVSZNA", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIOSZVSZNA(String value) {
        return new JAXBElement<String>(_TOEXOEIOSZVSZNA_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "RN", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIORN(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIORN_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DK", scope = TOEXOEIO.class)
    public JAXBElement<XMLGregorianCalendar> createTOEXOEIODK(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TOEXOEIODK_QNAME, XMLGregorianCalendar.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DL", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIODL(String value) {
        return new JAXBElement<String>(_TOEXOEIODL_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "DP", scope = TOEXOEIO.class)
    public JAXBElement<String> createTOEXOEIODP(String value) {
        return new JAXBElement<String>(_TOEXOEIODP_QNAME, String.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "PA", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOPA(Integer value) {
        return new JAXBElement<Integer>(_TRVERVXOPA_QNAME, Integer.class, TOEXOEIO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.egov.sk/mvsr/RFO/datatypes/Podp/Ext/PoskytnutieUdajovIFOOnlineWS-v1.0.xsd", name = "PG", scope = TOEXOEIO.class)
    public JAXBElement<Integer> createTOEXOEIOPG(Integer value) {
        return new JAXBElement<Integer>(_TOEXOEIOPG_QNAME, Integer.class, TOEXOEIO.class, value);
    }

}
