//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.30 at 01:17:27 PM CET 
//


package sk.is.urso.model.csru.api.sync.GetConsolidatedDataServiceSync;

import sk.is.urso.model.csru.api.sync.common.DataPlaceholderCType;
import sk.is.urso.model.csru.api.sync.common.FileCType;
import sk.is.urso.model.csru.api.sync.common.FileListCType;
import sk.is.urso.model.csru.api.sync.common.ParameterCType;
import sk.is.urso.model.csru.api.sync.common.ParameterListCType;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.is.urso.model.csru.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetConsolidatedDataRequest_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata_sync/v1.4", "GetConsolidatedDataRequest");
    private final static QName _GetConsolidatedDataResponse_QNAME = new QName("http://csru.gov.sk/csru_getconsolidateddata_sync/v1.4", "GetConsolidatedDataResponse");
    private final static QName _Base64Content_QNAME = new QName("http://csru.gov.sk/common/v1.4", "base64Content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.is.urso.model.csru.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetConsolidatedDataRequestCType }
     * 
     */
    public GetConsolidatedDataRequestCType createGetConsolidatedDataRequestCType() {
        return new GetConsolidatedDataRequestCType();
    }

    /**
     * Create an instance of {@link GetConsolidatedDataResponseCType }
     * 
     */
    public GetConsolidatedDataResponseCType createGetConsolidatedDataResponseCType() {
        return new GetConsolidatedDataResponseCType();
    }

    /**
     * Create an instance of {@link ParameterListCType }
     * 
     */
    public ParameterListCType createParameterListCType() {
        return new ParameterListCType();
    }

    /**
     * Create an instance of {@link ParameterCType }
     * 
     */
    public ParameterCType createParameterCType() {
        return new ParameterCType();
    }

    /**
     * Create an instance of {@link DataPlaceholderCType }
     * 
     */
    public DataPlaceholderCType createDataPlaceholderCType() {
        return new DataPlaceholderCType();
    }

    /**
     * Create an instance of {@link FileListCType }
     * 
     */
    public FileListCType createFileListCType() {
        return new FileListCType();
    }

    /**
     * Create an instance of {@link FileCType }
     * 
     */
    public FileCType createFileCType() {
        return new FileCType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConsolidatedDataRequestCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetConsolidatedDataRequestCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata_sync/v1.4", name = "GetConsolidatedDataRequest")
    public JAXBElement<GetConsolidatedDataRequestCType> createGetConsolidatedDataRequest(GetConsolidatedDataRequestCType value) {
        return new JAXBElement<GetConsolidatedDataRequestCType>(_GetConsolidatedDataRequest_QNAME, GetConsolidatedDataRequestCType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetConsolidatedDataResponseCType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetConsolidatedDataResponseCType }{@code >}
     */
    @XmlElementDecl(namespace = "http://csru.gov.sk/csru_getconsolidateddata_sync/v1.4", name = "GetConsolidatedDataResponse")
    public JAXBElement<GetConsolidatedDataResponseCType> createGetConsolidatedDataResponse(GetConsolidatedDataResponseCType value) {
        return new JAXBElement<GetConsolidatedDataResponseCType>(_GetConsolidatedDataResponse_QNAME, GetConsolidatedDataResponseCType.class, null, value);
    }

//    /**
//     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
//     *
//     * @param value
//     *     Java instance representing xml element's value.
//     * @return
//     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
//     */
//    @XmlElementDecl(namespace = "http://csru.gov.sk/common/v1.4", name = "base64Content")
//    public JAXBElement<byte[]> createBase64Content(byte[] value) {
//        return new JAXBElement<byte[]>(_Base64Content_QNAME, byte[].class, null, ((byte[]) value));
//    }

}
